#!/bin/bash

if ! type gmvault&>/dev/null;
then
    echo "gmvault is not installed please install it first";
    exit 1;
fi;


echo "this tool assumes your gmail settings have been configured to work with gmvault and that you have access to app password";

echo "enter your email";
read email;

echo "select what to do:";

select opt in "Sync Gmail to local Backup" "Recover lost emails" ; do
    if [ "$opt" = "Sync Gmail to local Backup" ]
    then
    gmvault sync -p "$email"
    else
    gmvault restore -p "$email"
    fi;
    break;
done;

